### ISSUE TITLE
send /me messages on Slack as /me on IRC

### ISSUE THREAD

**Issue by sknebel** [aaronpk/Slack-IRC-Gateway#17]
e.g. https://chat.indieweb.org/dev/2018-10-12#t1539369589615300 was a `/me` message in Slack

**Comment by aaronpk** [comment]
At some point, Slack stopped sending the `/me` text to the webhook and now sends only what's typed after that. They used to include the full typed out message like `/me waves` in the webhook, but that has changed. There is no longer any indication that the message used to have the `/me` text. They have also deprecated the web hooks API, so this will only be solvable if we switch over to the new [Events API](https://api.slack.com/events-api).

**Comment by aaronpk** [comment]
This works now that we switched to the Events API.
