### ISSUE TITLE
Feasibility of Keybase variant?

### ISSUE THREAD

**Issue by voxpelli** [aaronpk/Slack-IRC-Gateway#23]
I started thinking a but about the possibility of making a similar gateway like this, but for Keybase: https://github.com/keybase/keybase-bot

Do you think that would be possible? Any suggestions or thoughts?

**Comment by aaronpk** [comment]
Seems possible, but I want to focus this on just IRC and Slack. It wouldn't be hard to fork this and replace the Slack code with Keybase code though.
