### ISSUE TITLE
Shortened Slack URLs need to be expanded on IRC

### ISSUE THREAD

**Issue by Zegnat** [aaronpk/Slack-IRC-Gateway#24]
[Example message from tonight](https://chat.indieweb.org/dev/2021-06-09/1623197873941900):

> http://www.unmung.com/jsontoxoxo?url=https%3A%2F%2Fgranary.io%2Furl%3Finput%3Dhtml%[…]feed%253Dhttp%25253A%25252F%25252Fscripting.com%25252Frss.xml

The `[…]` in the middle of the URL is added by Slack, for display purposes only. In Slack, hovering the link will show the full URL, and clicking will also open this expended version.

![Screenshot: showing the expanded URL in Slack on hover.](https://user-images.githubusercontent.com/490579/121318370-7a620700-c90b-11eb-80db-076dee5a31af.png)

The actual full link that was expected was: http://www.unmung.com/jsontoxoxo?url=https%3A%2F%2Fgranary.io%2Furl%3Finput%3Dhtml%26output%3Djsonfeed%26url%3Dhttp%253A%252F%252Fwww.unmung.com%252Ffeed%253Ffeed%253Dhttp%25253A%25252F%25252Fscripting.com%25252Frss.xml

It is this expanded URL that should end up on IRC. Currently it leads to links unusable by chatters on IRC, as well as broken links in logging (e.g. the IndieWeb Chat logs).

**Comment by aaronpk** [comment]
We'll need to find the docs from Slack on this to know where to find the full URL. I'd also like to track down a change log from slack to find out when this changed, since it didn't do this before.

**Comment by jamietanna** [comment]
I've seen this happening on my work Slack for at least a couple of months, if it helps - and I seem to remember seeing this at least a few weeks ago on the IndieWeb Slack

**Comment by bkil** [comment]
You probably need to use `'$1'` here

* https://github.com/aaronpk/Slack-IRC-Gateway/blob/333bab7d9962f1b8c56f85ec3978d8f2f0d8a568/gateway.js#L393

according to 

* https://github.com/42wim/matterbridge/blob/89b0d362d29179b389b203e046b22b5b6e5f8310/bridge/slack/helpers.go#L184

**Comment by aaronpk** [comment]
Thank you, this was fixed in 84b905a95949f26976568aa3aec3d979eea6c61b
