### ISSUE TITLE
Gateway unconditionally echos messages without verifying they're from Slack [security?]

### ISSUE THREAD

**Issue by AbstractBeliefs** [aaronpk/Slack-IRC-Gateway#6]
Anyone who discovers where you're hosting the gateway can trigger messages with spoofed sender/content. Might be worth looking at ways to verify the endpoint was hit by Slack rather than anyone else.

Repro on request, let me know what suits you.

**Comment by aaronpk** [comment]
Thanks. I'll add some code to verify the token that Slack sends along with the web hook.
