### ISSUE TITLE
Use the slack RTM API in order to prevent lag between IRC and Slack

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/Slack-IRC-Gateway#8]
Using the RTM API will allow for the messaging between IRC and Slack to be more prioritized when Slack is having delays

**Comment by aaronpk** [comment]
This will also make #2 possible

**Comment by EdwardHinkle** [comment]
Notes for development:
- Part of this would need to be incorporating name and photo look up for irc users. Currently this is handled by the IRC bot not on the Slack side

Reference: https://github.com/aaronpk/TikTokBot#profile-data
Profile Data should be fetched from the microformats on the /irc-people page

**Comment by aaronpk** [comment]
Closing since we switched to the new Events API now.
